# only manual
trigger: none
pr: none

steps:
- task: Bash@3
  displayName: Install terraform
  inputs:
    targetType: 'inline'
    failOnStderr: false
    script: |
      TERRAFORM_VERSION="$(cat .terraform-version)"
      wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -v
      rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
- checkout: self
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS Prod'
    regionName: 'eu-south-1'
    scriptType: 'inline'
    inlineScript: |
      echo "##[section]Start terraform plan "
      cd src/main
      terraform init
      terraform apply
