# only manual
trigger: none
pr: none

steps:
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS Prod'
    regionName: 'eu-south-1'
    scriptType: 'inline'
    inlineScript: |
      echo "##[section]Start terraform plan "
